services:
  ash:
    image: ghcr.io/polarhive/ash:latest
    container_name: ash
    restart: unless-stopped
    working_dir: /app
    user: "${UID:-1001}:${GID:-1001}"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./bot.json:/app/bot.json:ro
      - ./blacklist.json:/app/blacklist.json:ro
      - ./data:/app/data
